name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    defaults: 
      run:
        working-directory: ./WiredBrain
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
    
    - name: Build
      run: dotnet build --configuration Release 
    
    - name: Publish API
      run: dotnet publish WiredBrain.Api/*.csproj --configuration Release 
    
    - name: Publish Portal
      run: dotnet publish WiredBrain.CustomerPortal.Web/*.csproj --configuration Release 
      
    - name: Publish Identity
      run: dotnet publish WiredBrain.Identity/*.csproj --configuration Release           

    - name: Upload API
      uses: actions/upload-artifact@v1.0.0
      with:
        name: WiredBrain-API
        path: WiredBrain.Api/bin/Release/netcoreapp3.0/publish
        
    - name: Upload Portal
      uses: actions/upload-artifact@v1.0.0
      with:
        name: WiredBrain-Web
        path: WiredBrain.CustomerPortal.Web/bin/Release/netcoreapp3.0/publish
        
    - name: Upload API
      uses: actions/upload-artifact@v1.0.0
      with:
        name: WiredBrain-Identity
        path: WiredBrain.Identity/bin/Release/netcoreapp3.0/publish
