name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    defaults: 
      run:
        working-directory: ./WiredBrain
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
    
    - name: Build
      run: dotnet build --configuration Release 
    
    - name: Publish API
      run: dotnet publish WiredBrain.Api/*.csproj --configuration Release 
    
    - name: Publish Portal
      run: dotnet publish WiredBrain.CustomerPortal.Web/*.csproj --configuration Release 
      
    - name: Publish Identity
      run: dotnet publish WiredBrain.Identity/*.csproj --configuration Release           
